# Generated by Django 3.2 on 2021-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.FileField(upload_to='FileDB'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='fileName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='upload',
            name='info',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
